### ISSUE TITLE
Failed to resolve: com.sina.weibo.sdk:core:4.2.7

### ISSUE THREAD

**Issue by FreeHotHeart** [zhanguangao/react-native-weibo-login#1]
Failed to resolve: com.sina.weibo.sdk:core:4.2.7

**Comment by zhanguangao** [comment]
Insert the following lines inside the allprojects block in android/build.gradle:
  maven { url "https://dl.bintray.com/thelasterstar/maven/" }

such as:
allprojects {
   repositories {
      mavenLocal()
      jcenter()
      maven { url "https://dl.bintray.com/thelasterstar/maven/" }
    }
}

**Comment by csyaonie** [comment]
Could not find com.sina.weibo.sdk:core:4.2.7.

**Comment by peachlsy** [comment]
Could not find com.sina.weibo.sdk:core:4.2.7.
  Required by:
      project :app > project :react-native-weibo-login

Although I installed everything step by step...
