### ISSUE TITLE
编译Xcode编译ios 提示相关符号找不到

### ISSUE THREAD

**Issue by fanzhiri** [zhanguangao/react-native-weibo-login#11]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_WBAuthorizeResponse", referenced from:
      objc-class-ref in libRCTWeiBo.a(RCTWeiBo.o)
  "_OBJC_CLASS_$_WBSendMessageToWeiboResponse", referenced from:
      objc-class-ref in libRCTWeiBo.a(RCTWeiBo.o)
  "_OBJC_CLASS_$_WBAuthorizeRequest", referenced from:
      objc-class-ref in libRCTWeiBo.a(RCTWeiBo.o)
  "_OBJC_CLASS_$_WeiboSDK", referenced from:
      objc-class-ref in libRCTWeiBo.a(RCTWeiBo.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zxcwdta** [comment]
I had this issue before and the way I fixed it is by creating a new scheme. Hopefully that will fix your problem as well.
