### ISSUE TITLE
第二次再调用login 返回参数里面就没有userId和access_token了

### ISSUE THREAD

**Issue by csyaonie** [zhanguangao/react-native-weibo-login#3]
第二次再调用login 返回参数里面就没有userId和access_token了，这也太过分了，至少返回userId不然我怎么知道是哪个用户在登录，微博的api太脑残了吧

**Comment by zhanguangao** [comment]
@csyaonie 如果第一次有userId和access_token的话，第二次那可能是调用频繁了限制返回了

**Comment by csyaonie** [comment]
@zhanguangao 谢谢你的回答 其实脑残的是我，根本没什么问题，亲测你这组件能用，谢谢你
